contentful/marketplace-partner-apps

apps/shopify/src/skuResolvers.js
Shopify app throws an error if a collection or product is missing. Due to this List is not rendered and the user is not able to remove missing products
=> fix: shopify app throw an error if collection or product is missing

apps/shopify/src/index.js
[Jira Ticket](https://contentful.atlassian.net/jira/software/c/projects/MONET/boards/384?modal=detail&selectedIssue=MONET-1253)
This PR adds eap Note prop to Shopify application.
Related PRs: 
- https://github.com/contentful/apps/pull/3802
- https://github.com/contentful/apps/pull/3803
How it looks 
After note is dismissed:
=> feat: add new prop for showing eap note [MONET-1253]

apps/ceros/package-lock.json, apps/ceros/package.json
Good read as to why react-scripts should be a dev dependency as it is a build tool and not a runtime checker - https://github.com/facebook/create-react-app/issues/11174
Security vulnerability brought up by dependabot https://github.com/contentful/marketplace-partner-apps/security/dependabot/184
Also downgrade typescript to 4.9 to resolve peer conflicting dependencies
Add explicit dependency for nth-check 2.01 that resolved that specific security vulnerability
None
=> [None] Fix ceros security vulnerability with nth-check and downgrade typescript to resolve conflicting peer dependencies

.github/dependabot.yml
Adds a dependabot.yml file that mirrors the configuration we had in the apps repo.
I kept the following configurations options under `ignore`: 
- Ignoring major semver updates
- Ignoring `@contentful/app-sdk` updates. It is configured this way in the apps repo, but I am open to changing it if we want.
=> chore: [INTEG-812] Add dependabot.yml file

apps/cloudinary2/.env.example, apps/cloudinary2/.gitignore, apps/cloudinary2/src/components/FieldWrapper.tsx, apps/cloudinary2/src/components/SelectField.tsx, apps/cloudinary2/src/components/TextField.tsx, apps/cloudinary2/src/constants.ts, apps/cloudinary2/src/locations/ConfigScreen/BackendConfiguration.tsx, apps/cloudinary2/src/locations/ConfigScreen/InstallParamsConfiguration.spec.tsx, apps/cloudinary2/src/locations/ConfigScreen/InstallParamsConfiguration.tsx, apps/cloudinary2/src/locations/ConfigScreen/helpers.ts, apps/cloudinary2/src/locations/ConfigScreen/index.tsx, apps/cloudinary2/src/types.ts, apps/cloudinary2/src/vite-env.d.ts
Changes
* Adds a new field "API Secret"
* Sends a request including the secret after save
* Components were extracted to the `components` folder
Notes
* Backend parameters are write-only, so the field is always empty after loading the config screen
* Explanations about what this does will be added in the future
* Backend will be created separately
Screenshot
=> feat(cloudinary2): save backend parameters

apps/bynder/src/index.js
When there are a lot of filters in the filter bar for the Bynder UCV, the whole dialog was scrolling horizontally and you couldn't see all of the features in the search bar above the filters. 
Added `overflow-x:auto` to the container div.
Before:
After:
Note that I could not add additional filters via our Bynder testing environment, so I added additional filters by creating new button elements in Dev Tools in order to replicate the issue. I also tested that adding the CSS property did not impact the Bynder UCV when there aren't too many filters in the top bar.
=> [INTEG-1152] Fix: Bynder horizontal scroll

apps/cloudinary2/.env.example, apps/cloudinary2/src/constants.ts, apps/cloudinary2/src/locations/ConfigScreen/index.tsx, apps/cloudinary2/src/vite-env.d.ts
When installing for the first time we need to wait for the installation to finish in order to utilize signed requests.
=> fix(Cloudinary): store API Secret after installation

apps/bynder/src/index.js
Reported bug in the Bynder app where when you use the search and only a few assets are displaying (so there are fewer columns), the content in the dialog shrinks in width.
Adjusted CSS for the `bynder-compactview` div to make `width: 100%`. See before and after below:
Before:
After:
1. Go to a space where the Bynder app is installed
2. Go to an entry and navigate to a field that's using the Bynder app
3. Click on "Select a file on Bynder" button
4. In the dialog, enter something in the search field that limits results to only a few assets
5. Confirm that the width of the content in the dialog doesn't change when there are only a few items displayed
None
=> fix: adjust Bynder dialog width [INTEG-1305]

.github/CODEOWNERS
@gavinmatt should be flagged for review for any PRs touching the apps folder
* Add @gavinmatt to codeowners. Multiple codeowners are "or" so this statement means either @gavinmatt _or_ @contentful/team-integrations is marked as codeowner
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> Make gavinmatt shared codeowner of apps

apps/bynder/package-lock.json, apps/bynder/package.json, apps/bynder/src/index.js
[This PR](https://github.com/contentful/apps/pull/5020) updated the `dam-app-base` with a new default for when there is no url/thumbnail image for an asset. This current PR bumps the `dam-app-base` in the Bynder app to utilize this change. It also changes the value of the alt text for the thumbnail to display the asset name instead of the asset id. Many of our other DAM apps return the asset name or a more readable Id from the `makeThumbnail` function.
The asset name is a friendlier thing for users to see when there is no thumbnail image to display. 
Before:
After:
Select an asset from Bynder that doesn't have a thumbnail image to see the new default asset in the entry. 
None, this is purely a visual change.
=> feat: new default selected asset displays asset name [INTEG-1405]

.circleci/config.yml
Partners are seeing build fails because of authorization issues with CircleCI checks. EG https://app.circleci.com/pipelines/github/contentful/marketplace-partner-apps/706/workflows/cbd48495-086f-4e4f-a384-87f3d31bcae2
Hard to know exactly what's causing this but I suspect it's the vault requirement that's hitting an auth problem. We actually don't even need access to the CI vault for any of our tests, so I want to try removing it. (If we do end up needing this access in CI I'll find out the hard way).
=> ci: remove unneeded vault access

.github/workflows/lint-pull-requests.yml, README.md
To in the future support better changelogs and more accurate version increments, our PR titles should be in conventional commit style: https://www.conventionalcommits.org/en/v1.0.0/#summary
Since we use PR titles for squash and merge, verifying the titles of our PRs is extra important.
* Use semantic-pull-request Github action https://github.com/marketplace/actions/semantic-pull-request
=> ci: add GH action to ensure PR titles are convetnional commits

apps/cloudinary2/src/locations/Field/Thumbnail.tsx
With the refreshed Cloudinary app, users can see additional file information in a menu for selected assets. Non-image assets don’t have format or dimensions data, so currently the menu information doesn’t look right for these assets.
Only show the format and dimensions data when it exists. See screenshots below.
Before:
After:
Select a non-image asset in Cloudinary. The file information in the menu should only show location, size, and created date. Any image or video asset should also display the format and dimensions.
=> fix: menu item display for non-image assets [INTEG-1415]

apps/surfer/src/components/SurferContainer.tsx, apps/surfer/src/locations/Sidebar.tsx, apps/surfer/src/types.ts
Disable an option for batch creating Surfer's Content Editors inside Contentful's app.
Our Surfer app is used on a specific content, tied to a single Content Editor. The batching feature doesn't make much sense in this context, while being problematic to display correctly in the sidebar's limited space. Creating a single CE is still available through the Contentful app and customers can find the batching feature in Surfer.
Bonus: fix the `Collapse` button being cut in some cases.
We're configuring the view to disable the `Create multiple` button.
In Dev mode:
1. Create new content with Surfer enabled
2. The only option to create a new CE should be `Create for 1 CE credit`
None
None, it's a bug we found since the first PR.
Nope
=> fix: disable batch creation of CEs (#3)

.github/semantic.yml
The purpose of this PR is to 
1. test that the Contentful semantic-pull-requests app works by ensuring we require the PR title to have semantic formatting and 
2. test that the custom configuration of the app enforces title check only, and that we are only going to refer to the PR title and not commits for the semantic info. This PR does not enforce any functionality of correct versioning, just enforces semantic commits. 
With this PR in particular as testing ground:
You will notice the title is formatted appropriately per semver standards. 
But when I changed it or did not have the correct formatting the PR check failed: 
Follow-up work to:
In order to ensure this compatible with the release-please functionality and conventional commits I would like to make sure of the following: 
1. …
=> chore: update semantic config

README.md, release-please-config.json
The purpose of this PR is to add the new ImageHotspotCreator app to the release-please configuration, as well as updated the README with instructions to do so when adding a new app.
=> chore: update release manifest and README

apps/flexfields/package-lock.json, apps/flexfields/package.json, apps/flexfields/src/locations/EntryEditor.tsx
Due to dependency issues with the richtextfield component in `default-field-editors`. This was fixed with a pr to the rich-text package to add the missing `@plate/common` dependency. 
This fix bumps the version number of `default-field-editors` to fix the rendering issue
=> fix: flexfields to render rich text fields

apps/flexfields/src/utils.ts
Flexfields tries to call `.getValue` on a field when `.value` is falsey. If a field that does not have `.getValue`, but they have an empty field, it will try to call`.getValue` resulting in an error.
Putting a `?` before invocation allows typescript to null-check if the method exists and then run it. So instead of `.getValue()` it is now `.getValue?.()`
=> fix: update isRuleValid to run getValue if it exists on the field

apps/shopify/src/index.js
The existing field on the app config page "API Endpoint" is confusing, users actually need to enter the Shopify store URL.
Update field name and description to be more clear about what needs to be entered in this field.
Ensured the app still worked as expected.
=> fix: update copy for store url [INTEG-1440]

.github/workflows/dependabot-approve-and-request-merge.yml
Per discussion in this thread https://github.com/cli/cli/issues/8352 the issue with our dependabot approve and merge might be that it lacks correct permissions.
* Try adding pull-request permission. See here https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
=> ci: add PR write permission to github action

.github/workflows/dependabot-approve-and-request-merge.yml
The experiment in #574 was a success, so we can now restore our action configuration to how it was before.
(See https://github.com/contentful/marketplace-partner-apps/pull/572 for an example that worked against that other branch of the action)
=> ci: restore v1 approver

.github/workflows/lint-pull-requests.yml
Linting PR rules were targeting our deploy (when we merge main into production). But we don't care about this. We only care about linting merges into the `main` branch.
Example failure: https://github.com/contentful/marketplace-partner-apps/actions/runs/7121013328/job/19389425649
Scope to main. See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
=> ci: only lint PRs that target the main branch

apps/uploadcare/src/locations/Dialog.tsx
A build error crept in for the uploadcare app and it's breaking the `main` branch: https://app.circleci.com/pipelines/github/contentful/marketplace-partner-apps/1377/workflows/4bb19a18-934c-43b3-88e6-7d805bb3cb09/jobs/1332
* Use a plain `CustomEvent` instead of specific type, since Typescript can't make the guarantee that the event listener will in fact receive event data that matches the provided type (See https://github.com/contentful/marketplace-partner-apps/blob/1d74d8cdb7278d53cbd40527f299b757c064313f/apps/uploadcare/src/locations/Dialog.tsx#L38-L44)
=> fix: type error in uploadcare build

.github/workflows/dependabot-approve-and-request-merge.yml
Small type on the permission name. Should be `pull-requests`. See https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
Add correct permission
Note: opened a PR here to fix our internal docs: https://github.com/contentful/github-auto-merge/pull/24
=> ci: fix permission name

.github/workflows/release-and-deploy.yml
Since we deploy to staging on all merges to main, we don't need to redeploy the same thing on the release please PR merge.
* Suppress staging deploy when releases are created
See https://docs.github.com/en/actions/learn-github-actions/expressions#operators
=> ci: don't deploy to staging on release

.github/CODEOWNERS
change DX codeownership to /apps/*/src & apps/*/public only to reduce PR noise from dependency upgrades
=> chore: change DX codeownership to /apps/*/src & apps/*/public only

apps/shopify/src/constants.js
Currently the Shopify Storefront API version that we are using, 01-2023, within the Shopify app has been deprecated as of January 1st, 2024. 
User's of the Shopify app are now receiving messages that they are interacting with a deprecated API. We therefore need to update this. 
I updated the API version to the latest version, in conjunction with a decision reached with the External References team, who will simultaneously update to the same version. The breaking changes that span the updates in the last year do not apply to our functionality. 
Question: How do we best keep track of these updates in the future? Since we don't receive these emails from Shopify, users do. A reminder? ticket?
Test that the Shopify app still works locally. 
To my knowledge after reading the changelog, there …
=> feat: upgrade shopify storefront API version

release-please-config.json
This PR adds the new Transifex app to the release-please config to support the initial release and future versioning of the app itself. Following this merge, an automated PR will be opened for initial release of the Transifex app at version number 1.0.0 and with a Changelog file added.
=> chore: add transifex to release please config

apps/transifex/package.json
This PR makes some adjustments to the Transifex deployment scripts that were not caught originally because of the specific vite vs webpack differences. The pipeline is currently not effectively deploying to the app definition because it is not referencing the right directory. See [these](https://github.com/contentful/marketplace-partner-apps/actions/runs/7467471120/job/20321063583) logs.
The build script doesn't need the mode configuration because `vite build` does production build automatically unless told otherwise so I removed that ([docs](https://vitejs.dev/guide/env-and-mode#:~:text=In%20some%20cases%2C%20you%20may,vite%20build%20%2D%2Dmode%20staging) for reference). The real fix comes in with referencing a `/dist` file as opposed to a `/build `directory in the deploy script, as the …
=> chore: adjust deployment scripts for Transifex

apps/transifex/package.json
The transifex app is not rendering effectively on the config page. We believe it is an issue of not using the appropriate env variables to make network calls. 
To ensure we are pointing to the production env, I have added the prod flag to the build script. 
This will not cause a breaking change.
=> chore: Adjust build script to explicitly point to prod env

apps/flexfields/src/components/RulesList.tsx, apps/flexfields/src/locations/ConfigScreen.tsx, apps/flexfields/src/locations/EntryEditor.tsx, apps/flexfields/src/types/Rule.tsx, apps/flexfields/src/utils.ts
1. Fix for https://github.com/contentful/marketplace-partner-apps/issues/642 - Show field customizations on FlexFields entry editor
2. Fix rules configuration for child entities from single reference fields.
3. Fix rules configuration and hiding fields for references to same content type.
1. Add help text for any field and/or custom true/false labels for boolean field in content type configured in FlexFields. It should now show up in the FlexFields entry editor.
2. Add reference field with single reference to content type configured in FlexFields. The content type(s) should be listed in the `Hide Field` section
3. Add reference field referencing the same content type. The entry editor should correctly hide fields in the same entry vs child entry based on the rule configured.
=> fix: Field customizations and additional config scenarios

apps/uploadcare/src/locations/Dialog.tsx
The main build has started failing due to a build error in Uploadcare: https://app.circleci.com/pipelines/github/contentful/marketplace-partner-apps/2263/workflows/152e6e91-3646-4f66-bc2a-c88c49223e67/jobs/1996?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary
The deeper issue here is that Typescript puts some restrictions on what kind of function can be assigned as an `EventListener`. It appears that `CustomEvent` used to work but now no longer does.
* Just use type assertions to handle the custom event sent from the uploadcare/blocks library
=> chore: fix customevent types to resolve build error

.github/dependabot.yml, .github/workflows/dependabot-approve-and-request-merge.yml, README.md
We have been ignoring major version upgrades in this repository for fear of shipping breaking updates.
* Allow dependabot to perform major version upgrades
* Prevent auto merging of major version upgrades, so they can be tested manually and deployed when ready
=> chore: allow dependabot to do major version upgrades

.github/dependabot.yml
When we introduced #810 we observed an unanticipated side effect: that dependabot was combining updates for the same dependency across multiple apps into a single PR. An example is here: https://github.com/contentful/marketplace-partner-apps/pull/814
Per our new guidance we will be asking app developers to approve major version updates to their dependencies individually. However, the grouping of PRs adds signficant friction to this process because we would require multiple reviewers on the same PR, and broken updates for a single app would hold up a change for all other updates in that PR.
* Force dependabot to treat packages individually by splitting the udpate directories explictily
* Use yaml anchor and alias to avoid repetition
* There's an added benefit here where e.g. we can specify …
=> chore: decouple dependabot updates per app

.github/dependabot.yml
We have a lot of dependabot PRs trying to push up types to v20, eg https://github.com/contentful/marketplace-partner-apps/pull/864
Types should match the supported version of node which is `v18.17`
* Pin to highest types package available for node 18
=> chore: pin node types to match supported node version (v18)

apps/adapt-essentials-asset-fields/package-lock.json, apps/adapt-essentials-asset-fields/package.json
…/apps/adapt-essentials-asset-fields (#838)"
This reverts commit 7cf2b757188dec4ecf40cdc9f83db5560eae3eed.
* Earlier PR actually broke the build and was mistakenly merged (because of wrong branch protections)
=> fix(deps): downgrade @contentful/app-sdk from 4.24.0 to 4.19.1 in apps/adapt-essentials-asset-fields (revert)

apps/flexfields/src/components/DefaultField.tsx, apps/flexfields/src/locations/ConfigScreen.tsx, apps/flexfields/src/locations/EntryEditor.tsx, apps/flexfields/src/utils.ts, apps/flexfields/test/mocks/mockSdk.ts
Fixes for https://github.com/contentful/marketplace-partner-apps/issues/707
1. Fix markdown field editor issues
2. Add locale support
3. Custom widgets - Display default widget when field configured to use custom UI
4. Fix field heading colour
5. Update relational fields to look like default entry editor
For custom widgets, the app framework does not support importing an app within an app. The workaround for now is to show the default widget for that field type and show an info message about this limitation.
=> fix: Field formatting, localization, custom widgets fallback

apps/flexfields/src/locations/ConfigScreen.tsx
Fix for https://github.com/contentful/marketplace-partner-apps/issues/702 
Create a rule for hiding fields in the same entry. Then edit that rule and confirm that the rule remains for same entry
https://github.com/contentful/marketplace-partner-apps/assets/31496466/80457d7e-edb8-4171-ae64-330b98908ee3
=> fix: Fix edit rule for same entry

apps/flexfields/src/locations/ConfigScreen.tsx, apps/flexfields/src/locations/EntryEditor.tsx, apps/flexfields/src/utils.ts, apps/flexfields/test/mocks/mockSdk.ts
Fix for https://github.com/contentful/marketplace-partner-apps/issues/931 
Setup
- Set a field to be `Hidden when editing` for a content type. 
- Configure that content type to have a rule in FlexFields.
Result
- The field should be hidden in the FlexFields entry editor. 
- It should also show when selecting `Show hidden fields` in editor options.
- When creating a rule, the hidden field is called out in the options to hide field
https://github.com/contentful/marketplace-partner-apps/assets/31496466/14faf645-bfc5-4195-a5fd-d583f29336a1
=> fix: Hide fields hidden for editing

.contentful/vault-secrets.yaml
This PR removes the `npm-read` vault policy from this repo. We are not using private packages in this repo so it should be able to be safely removed from here. 
As part the GH package migration we are removing `npm-read` from repos. We should be ok not replacing this with the new `packages-read` policy since this is a public repo that is not using private packages.
=> chore: remove npm-read from repo [INTEG-1822]

apps/adapt-essentials-asset-fields/src/components/MarkdownRender.tsx
Absolute images where not showing up in documentation. This PR fixes it. 
Removed absolute path I've hardcoded for development.
Go to app configuation page and confirm that you can see instructional images.
No breaking changes
https://github.com/adaptdk/adapt-essentials-asset-fields/issues/9
=> fix: Use relative path for documentation images in `Adapt Essentials: Asset Fields` app

apps/adapt-essentials-asset-fields/package-lock.json, apps/adapt-essentials-asset-fields/src/components/hooks/useLocales.tsx, apps/adapt-essentials-asset-fields/tsconfig.json
Resolve build issues for `dependabot/npm_and_yarn/apps/adapt-essentials-asset-fields/contentful/app-sdk-4.25.0` brach
Removed unused instance variable and changed lib target to ES2022 which was required by typescript compiler
Check if app loads
N/A
https://github.com/contentful/marketplace-partner-apps/pull/1042#issuecomment-1995751467
N/A
=> fix: Build for `bump @contentful/app-sdk from 4.19.1 to 4.25.0 in /apps/adapt-essentials-asset-fields`

apps/adapt-essentials-asset-fields/src/components/hooks/useLocales.tsx, apps/adapt-essentials-asset-fields/tsconfig.json
The developer of adapt-essentials-asset-fields resolved a major dep update issue in [this](https://github.com/contentful/marketplace-partner-apps/pull/1076) PR, but unfortunately we then merged this into an existing dependabot PR and dependabot is not a fan of that and will not rebase [this](https://github.com/contentful/marketplace-partner-apps/pull/1042) original PR 😢 . Therefore, I have recreated the developers changes here, to merge proactively - I will then rebase the original dependabot PR (which will overwrite the changes merged into it), and all will be well. Lesson learning about manipulating existing dependabot PRs 🙃
=> chore: resolve adapt-essentials-asset-fields locale issue

.github/dependabot.yml
The developer of the UploadCare app is requesting that dependabot ignores updates to a particular dependency: `@uploadcare/blocks` as per [this](https://github.com/contentful/marketplace-partner-apps/pull/1133#issuecomment-2001998656) comment. They would like this done in order to avoid future breaking changes, as an auto update to this API caused the app to break, given the API is v0/WIP. 
I have added this dependency to be ignored by auto updates within the UploadCare app. This configuration exists in the dependabot config specifically. 
Question: the same developer has expressed concerns that our dependabot would update a v0 dependency, given those are considered "unstable", see [this](https://github.com/contentful/marketplace-partner-apps/pull/1133) PR comment. Any immediate opinions …
=> chore: add dep to be ignored by dependabot

README.md
The purpose of this PR is to add in a bit more info around the expectations of contributors in managing dependency-related updates within this repository. There was a great deal of information provided already about dependency management, but I simply added a bit of color to approving the major version PRs informally, as well as resolving errors within them.
=> docs: add more info to dep update process in README

apps/shopify/package-lock.json, apps/shopify/package.json, apps/shopify/src/index.js
The placeholder text in the `ecommerce-app-base` was hardcoded so it was not reflecting the correct text for product variants and collections. We updated the `ecommerce-app-base` to have a configurable placeholder, and this PR implements that.
Bump the `ecommerce-app-base` and add `makeSearchPlaceholderText` to the `renderSkuPicker`. Also, I was running into an issue installing dependencies locally with this app due to a conflict with the `react-scripts` version and typescript version. I noticed that we are not using typescript in this app, so I removed the dependency and it is working now.
=> fix: placeholder text for Shopify SkuPicker [INTEG-2024]

apps/bynder/package-lock.json, apps/bynder/package.json
Update the Bynder app's version of react to 18, as well as update dam-app-base to v3.0.0
v3 of the dam-app-base is a breaking change for consumers that are on a version of react less than 18.0.0.  Fortunately for the dropbox app, we don't render any actual react code, instead depending on dam-app-base to render react code.  So no changes to the dropbox app necessary.
See [dam-app-base changelog](https://github.com/contentful/apps/blob/master/packages/dam-app-base/CHANGELOG.md#300-2024-05-07)
=> chore(bynder): upgrade to react v18 and dam-app-base v3

apps/transifex/src/locations/ConfigScreen.jsx
Remove the check for contentful space default locale match with transifex project source language, since they can be different now
Try to connect a transifex project with source language different from contentful space's default locale
=> feat: Transifex app remove the default locale restriction

apps/transifex/src/locations/ConfigScreen.jsx
Improve the error we get on configuration page when transifex project is deleted and app's installation has not been completed yet.
Display a relevant error message and allow users to reset selected project
- Install transisfex native app and connect it with a transifex project without completing the installation
- Delete transifex project
- On refresh user should see the following view
=> fix: Transifex app handle deleted project case

apps/bynder/package-lock.json, apps/bynder/package.json
Bump `dam-app-base` package in Bynder app to update app with fix to delete functionality from [this PR](https://github.com/contentful/apps/pull/7932).
I tested the app locally and confirmed that this fixes the issue with deleting selected assets. Also confirmed that key app functionality still works as expected.
We will need to merge in the `release-please` PR after this to deploy this changes.
=> fix: bump dam-app-base for delete functionality fix [ZEND-5025]

apps/shopify/package-lock.json, apps/shopify/package.json
Update Shopify app's version of react to 18, as well as update @contentful/ecommerce-app-base to > v4.0.0
drops support for react v16 || v17. 
drops support for @contentful/ecommerce-app-base v3
v3 -> v4 of the ecommerce-app-base is a breaking change for consumers that are on a version of react less than 18.0.0. Fortunately for the shopify app, we don't render any actual react code, instead depending on ecommerce-app-base to render react code. So no changes to the shopify app necessary.
Tested locally by installing react & react-dom v18.2.0, and @contentful/ecommerce-app-base v4.0.6.
=> build!: update shopify to react v18 and @contentful/ecommerce-app-base v4

apps/flexfields/src/locations/ConfigScreen.tsx
1. Allow multi-reference fields to be used in the rule condition.
2. Add Select/deselect all option in the hide field dropdown.
1. Removed a filter that restricted showing multi-reference fields.
2. `Multiselect.SelectAll` was used as part of the forma36 multi-select component.
1. Create a content type with a multi-reference field. Open the FlexFields configuration screen and select the content type. The multi-reference field should show up in the `With field` dropdown.
2. When configuring the rule, the `Hide field` dropdown should show the `Select all` option when `With content type` is selected.
=> feat: Allow multi-reference field for condition and include Select all option for hide field

apps/flexfields/src/components/DefaultField.tsx
The FlexFields entry editor was blank when the content type included a JSON field. 
Using the JSON field editor explicitly instead of the default field editor for JSON field
Add JSON field to a content type. Add a rule in FlexFields and verify that the editor displays appropriately.
=> fix: Fix blank editor if Json field is present

.github/dependabot.yml
This PR adds two apps to the dependabot.yml: Amplitude and Xilio Transcreate. This will then mean that the updates for these apps will be separate from other apps so that we can merge these in isolation and have the partner developers look at the PRs for their apps. I also updated the timezone for all dependabot PRs since `UTC` was showing as invalid in VS Code.
=> chore: update dependabot with new apps and change to valid timezone []

apps/cloudinary2/src/constants.ts
Customers have asked for AVIF thumbnail support in the cloudinary app [CCS-1240]
It's already supported on Cloudinary, just needed to update the list of allowed files
[CCS-1240]: https://contentful.atlassian.net/browse/CCS-1240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Added support for AVIF image thumbnails [CCS-1240]

apps/transifex/package-lock.json, apps/transifex/package.json
Removes dependency on unmaintained `emotion` package, replaces it with `@emotion/css`
=> chore: remove vulnerable dependencies for transifex

apps/voucherify/.npmrc, apps/voucherify/index.html, apps/voucherify/package-lock.json, apps/voucherify/package.json, apps/voucherify/test/vite.setup.js, apps/voucherify/vite.config.js
Removes dependency on unmaintained react-scripts package, replaces it with `vite`/`vitest`
=> chore: replace vulnerable dependencies for voucherify

.nvmrc
since our `.npmrc` dictates `engine-strict=true`, make sure we're always allowing the latest v18 LTS
=> chore: bump node to v18 LTS

.github/workflows/app-review-utils.ts, .github/workflows/new-app-review/index.ts
This is a tweak to the New App Review check that was recently added in https://github.com/contentful/marketplace-partner-apps/pull/2480. It ensures only new apps go through these checks.
Ended up being little tricky to determine if an app is new because the github rest api does not return directories in their pr listFiles method. We opted to just check if a new package.json file was added. 
1. Submit a change to an existing app - checks should NOT run.
2. Submit a new app with a package.json file - checks should run.
=> fix: only consider PRs to be for new apps if they contain a new package.json [EXT-5337]

apps/ceros/.npmrc, apps/ceros/index.html, apps/ceros/package-lock.json, apps/ceros/package.json, apps/ceros/src/react-app-env.d.ts, apps/ceros/src/styles.ts, apps/ceros/src/vite-env.d.ts, apps/ceros/test/vite.setup.ts, apps/ceros/tsconfig.json, apps/ceros/vite.config.js
Removes dependencies on unmaintained react-scripts and emotion packages. Replaces react-scripts with vite/vitest. Replaces emotion with @emotion/css
=> chore: remove vulnerable dependencies for ceros

apps/surfer/.env.production, apps/surfer/index.html
Due to migration from react-scripts to vite, env variable was not injected to html template (by default VITE injects only envs that start with `VITE` (https://vitejs.dev/guide/env-and-mode))
Followed default vite behavior.
Simply build the app by running `npm run build` and inspect `build/index.html` output file (check src of script tag in head).
Contentful x Surfer app will work again 😁 
PR with react-scripts -> vite migration: https://github.com/contentful/marketplace-partner-apps/pull/2469
=> fix: Prefix env variable with 'VITE' to be injected

apps/raster/src/locations/ConfigScreen.tsx
The Raster icon on the config page wasn't loading. This PR updates the path to the icon so that it references it properly and it renders.
Uploaded the bundle with this change to a testing app and confirmed that the logo is visible on the config page.
=> fix: update path for raster icon [EXT-5671]

.github/workflows/new-app-review.yml, .github/workflows/release-and-deploy.yml
- new-app-review workflow needs a minor tweak to execute in the correct working directory
- release-and-deploy workflow was complaining about the release-type not being specified
=> fix: use cwd for new-app-review workflow, specify node release type for release-and-deploy workflow [EXT-00]

apps/frontify/README.md, apps/frontify/package.json
The frontify team is working on a fix for their v2 app. For now, I propose we simply remove the deployment path, which will allow for a cleaning commit diff in the future when they introduce a fix
=> chore: remove deployment path for frontify v2

apps/flexfields/src/locations/EntryEditor.tsx
The field created by this app are thiner than the original fields
provide the same width for flexfields as for the original contentful fields
it's just a minor css fix
none
none
no deploment changes
=> fix: styling in flexfields: wrapper-width

apps/eppo/src/locations/EntryEditor/EntryEditor.tsx
This is a simple simplification to the Eppo feature flag key name generatio to replace multiple subsequent dashes with a single dash, eg.: `flag---key` becomes `flag-key`
This is simple enough that it requires no additional context. It should have no visible customer impact.
N/A
None
=> chore(eppo): Simplify flag key generation

apps/amplitude-experiment/README.md, apps/amplitude-experiment/package.json, apps/amplitude-experiment/src/contexts/ExperimentContext.tsx, apps/amplitude-experiment/src/locations/EntryEditor.tsx, apps/amplitude-experiment/src/locations/Sidebar.tsx, apps/amplitude-experiment/src/utils/amplitude.ts
This change will add support for feature flags in the Amplitude Experiment plugin, which currently only supports experiments.
Feature flag related resources are fetched and displayed as options
To test this app, you can run this app locally by running yarn install && yarn start and create an app definition pointing to localhost:5173.
No breaking changes are expected
Amplitude Experiment [documentation](https://amplitude.com/docs/feature-experiment/contentful)
N/A
=> feat: Amplitude Experiment - add support for feature flags

.github/workflows/new-app-review.yml, package-lock.json, package.json
=> chore: app review workflow works for forked branches[INTEG-2165]

apps/growthbook/src/locations/Sidebar.tsx
A customer set the wrong Growthbook API server.  The server they put returned non-JSON response which failed to respond. The Growthbook API  server should always return JSON, if the server is not returning JSON then they probably do not have the right server, and hence this PR adds a better error message telling them to check that the server is correct.
We could have tried catching the error when we json decode and then rethrow a more detailed message, this approach of just checking the message for "is not valid JSON" is probably good enough.
In plugin settings put in "cdn.growthbook.io".  Then create a new "Growthbook Experiment" content entry.  Add a title, and two variations and then click "Create Experiment"
None
None
None
=> feat: Better error message when server does not return JSON []

apps/growthbook/src/locations/Sidebar.tsx, apps/growthbook/tests/locations/Sidebar.spec.tsx
A user added Growthbook Experiment Sidebar to a different content model.  The sidebar then errored.  This adds a warning that it only works on "Growthbook Experiment" content type, and provides a link to remove it from the current content model if it is not correct.  
We check the content type and show the warning if it is the wrong one.  
`yarn test`
Add "Growthbook Experiment" to the sidebar of a different content type.  
Create an entry of that type.
See the warning in the entry, with the correct content type name.
Click the link and see it goes back to editing that content types sidebar.
Create a Growthbook Experiment Content type entry.
See the warning does not show when editing that entry.
None
None
None
=> feat: Show warning when Growthbook sidebar is used in other content models []

.github/dependabot.yml
Some apps in this repo are supported by Contentful. When dependabot PRs are open it would be nice to see at a quick glance whether or not the PR is something we can approve and update that dependency ourselves versus getting approval from the app developer. I added a label to the apps we own that have a dependabot configuration.
=> feat: adds labels to dependabot prs for contentful owned apps [INTEG-2430]

.github/workflows/pr-title-check.yml
Dependabot PRs are all failing the pr title workflow check to enforce attaching JIRA tickets. We shouldn't enforce this for dependabot PRs.
=> fix: don't run pr title check workflow for dependabot PRs [INTEG-2430]

.github/workflows/pr-title-check.yml
The title workflow was still running on dependabot PRs after merging in my attempted fix. I asked github copilot in the pr title check failure why it ran on the PR and it suggested this corrected syntax for the if condition. hopefully this one works!
=> fix: syntax for avoiding running pr title check on dependabot [INTEG-2340]

apps/docs-to-rich-text/package-lock.json, apps/docs-to-rich-text/package.json, apps/docs-to-rich-text/src/api/licensing.ts, apps/docs-to-rich-text/src/locations/ConfigScreen.spec.tsx, apps/docs-to-rich-text/src/locations/ConfigScreen.tsx, apps/docs-to-rich-text/src/locations/Field.spec.tsx, apps/docs-to-rich-text/src/locations/Field.tsx, apps/docs-to-rich-text/src/types.ts, apps/docs-to-rich-text/src/utils/editorInterfaceUtil.ts, apps/docs-to-rich-text/src/utils/imageUpload.ts, apps/docs-to-rich-text/test/api/licensing.spec.ts
This change adds two new features to the Docs to Rich Text app:
1. Enhanced configuration page to allow users to easily enable the Docs to Rich Text appearance editor for their rich text fields
2. A warning icon is displayed on rich text fields that have restrictions configured, to warn users that importing may result in validation errors 
- The enhanced configuration page allows users fine-grained control over where the Docs to Rich Text appearance editor is used without the hassle of having to individually modifying every rich text field on every content model.
- The warning icon gives users an indication of why validation errors might occur.
1. Install the application
2. Navigate to the configuration page
3. See that a new section for "Configure Rich Text Fields" now exists
4. Enable …
=> feat: Enhance app configuration page []

.github/workflows/delete-branch-on-close.yml, .github/workflows/dependabot-approve-and-request-merge.yml
When dependabot puts up a PR that is theoretically auto-merge-able (minor dependency bump) the auto merge feature is failing because the "automatically delete branch" portion of the workflow fails. That apparently results in the PR failing to merge entirely rather than just failing to delete the branch. 
There are two parts here:
A new workflow that deletes branches on merge into main rather than attempting to do it when added to the merge queue Customizing our dependabot auto merge job to not attempt to delete the branch so it doesn't fail
=> fix: adds workflow to close branches after merge [INTEG-2453]

.github/workflows/dependabot-approve-and-request-merge.yml
A fix for my attempt at disabling the delete-branch logic that comes from the contentful/github-auto-merge package
=> fix: syntax for approve and request merge workflow [INTEG-2453]

apps/docs-to-rich-text/package-lock.json, apps/docs-to-rich-text/package.json, apps/docs-to-rich-text/src/locations/ConfigScreen.tsx, apps/docs-to-rich-text/src/utils/editorInterfaceUtil.ts
Resolves two issues on the configuration screen:
1. Configuration screen should handle being displayed in a pre-installation state
2. Calls to `cma.appDefinition.get({ appDefinitionId: sdk.ids.app });` fail on the configuration page with a 404 error (installation state irrelevant), for an unknown reason. This call succeeds when the app is installed locally, but not when released by the marketplace.
Issue 1 - Configuration screen should handle being displayed in a pre-installation state
To address this `sdk.app.isInstalled()` is used to determine the installation state, and components are reactively displayed based on this state.
Issue 2 - Calls to `cma.appDefinition.get({ appDefinitionId: sdk.ids.app });` fail on the configuration page with 404 error
I was unable to determine why this api …
=> fix: Docs to Rich Text - Resolves bugs on configuration screen []

.github/CODEOWNERS
Updates ownership to new marketplace team in github. We need to change delivery teams at the same time so don't merge this unless you know that is happening
=> chore: Update CODEOWNERS to mktp (SEE NOTE BEFORE MERGING) []

apps/eppo/LICENSE, apps/eppo/src/components/EppoEntrySelector/index.tsx, apps/eppo/src/components/modified/useEditorPermissions.tsx, apps/eppo/src/constants.ts, apps/eppo/src/helpers/get-api-base-url.ts, apps/eppo/src/hooks/useEntryEditorPermissions.tsx, apps/eppo/src/locations/ConfigScreen.tsx, apps/eppo/src/locations/EntryEditor/EntryEditor.tsx, apps/eppo/src/locations/EntryEditor/FinishConfigSetup.tsx, apps/eppo/src/locations/EntryEditor/OptionalTreatmentVariation.tsx
Customers want the ability to enforce content-type validations in the "Control" and "Treatment" variations of their eppo experiments. 
This PR also contains a separate piece of work that shows users an error screen if they have not finished configuring their app
Use the EntryEditorSDK to find the field validations necessary to limit by content-type
- Edit `Default Variation (control)` field of the content model for `Eppo variant container`
- Check `Accept only specified entry type` and select specific content types
- Expect that only these content types are allowed in both Control and Treatment variations when filling out an `Eppo variant container` entry.
None
None
None
=> fix(eppo): enforce content-type validations in variants []

apps/bynder-content-workflow/package-lock.json, apps/bynder-content-workflow/package.json, apps/bynder-content-workflow/src/appVersion/appVersion.ts, apps/bynder-content-workflow/src/utils/entriesImport.spec.ts, apps/bynder-content-workflow/src/utils/parser.ts, apps/bynder-content-workflow/vite.config.ts
This is fixing a bug with the Content Workflow Bynder integration where if the user had italic content in their fields in Content Workflow the import would throw a validation error.
We used to have an override for the `em` tag to create a nested paragraph. This isn't compatible with the Contentful API so instead dropping our custom handler and bumping the `contentful-rich-text-html-parser` to the latest release which has `em` support already.
You would need a Content Workflow account but simply put italic content into a Content Workflow item field, then setup the template mapping between the Content Workflow and Contentful. Then when you try to import the content it would break.
Not as far as I can tell, tested everything on my local to ensure it all worked.
Sorry all internal tickets …
=> fix: Italics in content causes a validation error when importing [INTEG-2515]

.gitignore, apps/shopify/jest.config.js, apps/shopify/package-lock.json, apps/shopify/package.json, apps/shopify/src/__tests__/setup.js, apps/shopify/src/__tests__/skuResolvers.test.js, apps/shopify/src/basePagination.js, apps/shopify/src/collectionPagination.js, apps/shopify/src/constants.js, apps/shopify/src/index.js, apps/shopify/src/productPagination.js, apps/shopify/src/productVariantPagination.js, apps/shopify/src/skuResolvers.js, apps/shopify/src/utils/validation.js, apps/shopify/tsconfig.json
- Shopify is deprecating the Buy SDK with a hard deadline of July 1st, 2025
- This PR migrates our Shopify integration from the deprecated shopify-buy to the modern @shopify/storefront-api-client@^1.0.2.
Shopify staging space 👉 [here](https://app.contentful.com/spaces/uy78qx6u62f3/views/entries)
1. **Install/Configure App**: Set up Shopify app with valid store credentials
2. **Product Selection**: 
- Open Contentful entry with Shopify SKU field
- Search for and select products from Shopify store
- Verify product data displays correctly (title, images, pricing, variants)
3. **Collection Selection**:
- Select Shopify collections 
- Confirm collection metadata and product counts display
4. **Variant Selection**:
- Choose specific product variants
- Verify variant-specific data (SKU, pricing, …
=> refactor: replaced the Buy SDK with Storefront [INTEG-2706]

apps/vwo-fme/src/components/CreateContent.js, apps/vwo-fme/src/locations/EntryEditor.jsx, apps/vwo-fme/src/utils.js, apps/vwo-fme/src/vwo-client.js
We introduced this change to address a bug where the API response payload was inconsistent, leading to broken integration in certain client applications. Updating the payload format ensures a more reliable and predictable structure for downstream consumers. This fix is part of ongoing efforts to stabilize the API and reduce ambiguity in how data is parsed and used.
We updated the structure of the returned JSON payload to match the latest API design guidelines. Rather than patching the old format, we refactored the relevant serializers to produce a clean and semantically accurate payload. This allows better compatibility with modern consumers and lays the groundwork for future enhancements. We considered backward compatibility wrappers but opted for a clean break to maintain long-term …
=> fix: update API payload structure to resolve data handling issue []

.github/workflows/dependabot-approve-and-request-merge.yml
None of our minor version bump PRs are getting automatically approved + merged due to our merge queue in this repo. This update just takes what we have in the github-auto-merge repo and edits it to fit our use case of not deleting branches.
=> chore: don't delete branches for approve and request merge dependabot workflow []

.github/workflows/yaml-linter.yml, .yamllint.yaml
Changes
- Increase allowed line width in workflow yaml files from 80 to 120 characters
- Throw warnings instead of errors when a workflow has lines wider than 120 characters
I was seeing errors like this in workflow actions ([for example](https://github.com/contentful/marketplace-partner-apps/actions/runs/15857675575/job/44706920017?pr=5236)):
```
lint: error: failed yamllint on .github/workflows/*.yml.
.github/workflows/dependabot-approve-and-request-merge.yml
Error: 22:81 [line-length] line too long (97 > 80 characters)
Error: 25:81 [line-length] line too long (82 > 80 characters)
Error: 31:81 [line-length] line too long (97 > 80 characters)
Error: 41:81 [line-length] line too long (100 > 80 characters)
Error: 44:81 [line-length] line too long (97 > 80 characters)
Error: 59:81 …
```
=> chore: increase line width in yaml linter config [INTEG-2829]

.github/workflows/release-please-auto-merge.yml
Automates releases for dependency-only updates from Dependabot
- Only runs for `github-actions[bot]` on `'chore: release'` PRs
- Blocks execution on forked PRs for security
- Checks for `**deps**:` pattern in PR description to confirm dependency updates
- Skips PRs with Features, Reverts, or BREAKING CHANGE sections
- Defaults to manual review if validation fails
Copied from [dependabot-approve-and-request-merge.yml](https://github.com/contentful/marketplace-partner-apps/blob/main/.github/workflows/dependabot-approve-and-request-merge.yml) with some slight adjustments:
- Auto-approves via `contentful-automation[bot]`
- Uses repository default merge method (instead of doing the "Get merge type" step)
=> chore: auto-merge dependency-only updates [INTEG-2829]

.release-please-manifest.json, apps/statsig/CHANGELOG.md, apps/statsig/package-lock.json, apps/statsig/package.json
Reverts contentful/marketplace-partner-apps#5769
=> fix: Revert "chore: release  statsig 1.1.5 []"

apps/statsig/package-lock.json, apps/statsig/package.json, apps/statsig/src/components/field-editor-reference/components/CreateEntryLinkButton/CreateEntryLinkButton.tsx, apps/statsig/src/components/field-editor-reference/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx, apps/statsig/src/components/field-editor-reference/components/LinkActions/redesignStyles.ts, apps/statsig/src/components/field-editor-reference/components/LinkActions/styles.ts, apps/statsig/src/components/field-editor-reference/components/MissingAssetCard/styles.ts, apps/statsig/src/components/field-editor-reference/components/SpaceName/SpaceName.tsx, apps/statsig/src/components/forma-36-menu/MenuDivider/MenuDivider.styles.ts, apps/statsig/src/components/forma-36-menu/MenuDivider/MenuDivider.tsx, apps/statsig/src/components/forma-36-menu/MenuItem/MenuItem.styles.ts, apps/statsig/src/components/forma-36-menu/MenuItem/MenuItem.tsx, apps/statsig/src/components/forma-36-menu/MenuList/MenuList.styles.ts, apps/statsig/src/components/forma-36-menu/MenuList/MenuList.tsx, apps/statsig/src/components/forma-36-menu/MenuList/MenuListFooter.tsx, apps/statsig/src/components/forma-36-menu/MenuList/MenuListHeader.tsx, apps/statsig/src/components/forma-36-menu/MenuSectionTitle/MenuSectionTitle.styles.ts, apps/statsig/src/components/forma-36-menu/MenuSectionTitle/MenuSectionTitle.tsx, apps/statsig/src/components/forma-36-menu/SubmenuTrigger/SubmenuTrigger.styles.ts, apps/statsig/src/components/forma-36-menu/SubmenuTrigger/SubmenuTrigger.tsx, apps/statsig/src/components/forma-36-popover/PopoverContent/PopoverContent.styles.ts, apps/statsig/src/components/forma-36-popover/PopoverContent/PopoverContent.tsx, apps/statsig/src/locations/EntryEditor/styles.ts
Statsig reported their app won't load, due to dependabot updating their emotion library to version 11. it has breaking changes with how emotion is imported.
I had some difficulties reverting this properly with all of the versioning PRs, other dependabot changes, etc. so I just went ahead and made the updates necessary to support v11. tested on staging and the app is loading now.
=> fix: statsig emotion library updates []

apps/transifex/src/locations/ConfigScreen.jsx, apps/transifex/src/locations/Sidebar.jsx
To be consistent with transifex contentfull standalone app, use everywhere the actual environment id instead of environment alias
When initializing the CMA client, ensure the actual environment.id is used instead of the alias.
The installation of contentful native app should work as expected
=> feat: Transifex  app handle environment alias [INTEG-001]
