- apps/bynder/LICENSE
- apps/cloudinary/LICENSE
- apps/shopify/LICENSE
Keep the LICENSE years up to date
None
None
None
Standard deployment
> [INTEG-750] Update LICENSE years to 2023

- apps/cloudinary/src/index.js
Support ticket request to increase the size https://contentful.atlassian.net/browse/INTEG-301
Just update the constant
Smoke test the app
None
None
Standard
> [INTEG-301] Allow 1000 max file limit per field for Cloudinary

- apps/cloudinary/src/index.js
Small fix to the UI to make sure it says the correct max file limit number.
Simple smoke test of the app
Smoke test the app
None
None
Standard
> [FIX] Format the index.js file and update the max file limit setup

- apps/cloudinary/src/index.js
Update prod to match main
Smoke test app
None
None
Standard
> [Prod] Format the index.js file and update the max file limit setup

- .gitignore
- apps/bynder/package-lock.json
- apps/bynder/package.json
- apps/ceros/package-lock.json
- apps/ceros/package.json
- apps/cloudinary/package-lock.json
- apps/cloudinary/package.json
- apps/cloudinary2/package-lock.json
- apps/cloudinary2/package.json
- apps/cloudinary2/src/locations/ConfigScreen/helpers.ts
- apps/shopify/package-lock.json
- apps/shopify/package.json
- apps/shopify/src/additionalDataRenderer.js
- apps/shopify/src/constants.js
- apps/shopify/src/dataTransformer.js
- apps/shopify/src/index.js
- apps/shopify/src/skuResolvers.js
Update the production branch to benefit from https://github.com/contentful/marketplace-partner-apps/pull/215.
> Production merge with product card v2 for shopify

- apps/shopify/src/index.js
Actually switching to the new product card.
> feat(Shopify): switch to v2 product card

- apps/bynder/package-lock.json
- apps/bynder/src/index.js
- apps/ceros/package-lock.json
- apps/ceros/package.json
- apps/cloudinary/package-lock.json
- apps/cloudinary2/package-lock.json
- apps/cloudinary2/package.json
- apps/shopify/package-lock.json
- apps/shopify/src/index.js
Put https://github.com/contentful/marketplace-partner-apps/pull/239 into production.
> Production merge use v2 product card for shopify

- apps/cloudinary2/src/locations/ConfigScreen/BackendConfiguration.tsx
- apps/cloudinary2/src/locations/ConfigScreen/InstallParamsConfiguration.spec.tsx
- apps/cloudinary2/src/locations/ConfigScreen/InstallParamsConfiguration.tsx
- apps/cloudinary2/src/locations/ConfigScreen/index.tsx
Move API secret next to the key and add description.
> feat(cloudinary): more clarity on API key+secret

- apps/cloudinary2/package-lock.json
- apps/cloudinary2/package.json
- apps/cloudinary2/src/App.tsx
- apps/cloudinary2/src/locations/Field/index.tsx
When opening the menu from the Thumbnail the iframe is flickering. Working some CSS magic to fix that.
> fix(Cloudinary): prevent flickering when opening dialog

- apps/bynder/src/index.js
- apps/ceros/package-lock.json
- apps/ceros/package.json
- apps/cloudinary2/.env.example
- apps/cloudinary2/package-lock.json
- apps/cloudinary2/package.json
- apps/cloudinary2/src/App.tsx
- apps/cloudinary2/src/constants.ts
- apps/cloudinary2/src/locations/ConfigScreen/index.tsx
- apps/cloudinary2/src/locations/Field/index.tsx
- apps/cloudinary2/src/vite-env.d.ts
- apps/shopify/package-lock.json
- apps/voucherify/package-lock.json
- apps/voucherify/package.json
Brings production up to date with main branch.
I tested the following apps in our staging environments to ensure that they were still working properly:
- Bynder
- Ceros
- Shopify
- Voucherify
> Production merge bynder fix

- apps/uploadcare/.eslintrc.json
- apps/uploadcare/.gitignore
- apps/uploadcare/.prettierrc.json
- apps/uploadcare/CHANGELOG.md
- apps/uploadcare/LICENSE
- apps/uploadcare/OVERRIDES.md
- apps/uploadcare/README.md
- apps/uploadcare/package-lock.json
- apps/uploadcare/package.json
- apps/uploadcare/public/index.html
- apps/uploadcare/src/App.tsx
- apps/uploadcare/src/assets/logo.svg
- apps/uploadcare/src/components/LocalhostWarning.tsx
- apps/uploadcare/src/constants.ts
- apps/uploadcare/src/index.tsx
- apps/uploadcare/src/locations/ConfigScreen/Configuration.tsx
- apps/uploadcare/src/locations/ConfigScreen/FieldSelector.tsx
- apps/uploadcare/src/locations/ConfigScreen/NoContentTypes.tsx
- apps/uploadcare/src/locations/ConfigScreen/fields.ts
- apps/uploadcare/src/locations/ConfigScreen/index.tsx
- apps/uploadcare/src/locations/Dialog.tsx
- apps/uploadcare/src/locations/Field/OpenDialogButton.tsx
- apps/uploadcare/src/locations/Field/ParamsValidationNotes.tsx
- apps/uploadcare/src/locations/Field/Thumbnail.tsx
- apps/uploadcare/src/locations/Field/Thumbnails.tsx
- apps/uploadcare/src/locations/Field/index.tsx
- apps/uploadcare/src/react-app-env.d.ts
- apps/uploadcare/src/types.ts
- apps/uploadcare/src/utils.ts
- apps/uploadcare/tsconfig.json
Hey! We are Uploadcare and we want to add this integration to Contentful Marketplace.
We contacted with Matt Middleton and they said that first we should send a PR with out app for review.
It seems like there is the only way for us to integrate with Contentful — “bind” our File Uploader to Contentful JSON object field. It is the same way you folks did together with Cloudinary, Bynder, etc.
Here are the testing steps for the case where you server the app on localhost using dev server:
1. Create an account in Contentful. You also need to create a space there. If you have things like “Content types” and “Content” and you can create that things, you've done.
2. Clone the repo and install the deps for this app.
3. Run start script from the /apps/uploadcare directory.
4. Go to your management …
> Add Uploadcare app

- .circleci/config.yml
- apps/cloudinary/package.json
- apps/cloudinary2/package.json
> feat(Cloudinary): switch to Cloudinary v2

- apps/flexfields/package-lock.json
Reverts contentful/marketplace-partner-apps#326 which breaks master
> Revert "fix(deps): bump @contentful/default-field-editors from 1.2.62 to 1.5.8"

- apps/ceros/package-lock.json
- apps/ceros/package.json
- apps/cloudinary/package-lock.json
- apps/cloudinary/package.json
- apps/cloudinary2/package-lock.json
- apps/cloudinary2/package.json
- apps/flexfields/package-lock.json
- apps/flexfields/package.json
- apps/shopify/package-lock.json
- apps/shopify/package.json
- apps/surfer/package-lock.json
- apps/surfer/package.json
- apps/uploadcare/package-lock.json
- apps/uploadcare/package.json
- apps/voucherify/package-lock.json
- apps/voucherify/package.json
> Release PR to prod

- apps/bynder/package-lock.json
- apps/bynder/package.json
- apps/bynder/src/index.js
- apps/cloudinary/package-lock.json
- apps/cloudinary2/package-lock.json
- apps/cloudinary2/package.json
- apps/shopify/package-lock.json
Brings production up to date with main branch.
Verified that Bynder app is functioning normally in staging.
> Production merge with Bynder update

- .circleci/config.yml
- .github/workflows/lint-pull-requests.yml
- README.md
- apps/bynder/package-lock.json
- apps/ceros/package-lock.json
- apps/ceros/package.json
- apps/cloudinary/package-lock.json
- apps/cloudinary2/package-lock.json
- apps/cloudinary2/package.json
- apps/cloudinary2/src/locations/Field/Thumbnail.tsx
- apps/flexfields/package-lock.json
- apps/flexfields/package.json
- apps/shopify/package-lock.json
- apps/shopify/package.json
- apps/surfer/package-lock.json
- apps/surfer/package.json
- apps/surfer/src/components/SurferContainer.tsx
- apps/surfer/src/locations/Sidebar.tsx
- apps/surfer/src/types.ts
- apps/uploadcare/package-lock.json
- apps/uploadcare/package.json
- apps/voucherify/package-lock.json
- apps/voucherify/package.json
> Updates to Cloudinary and Surfer apps and dependencies/CI changes

- .github/workflows/release-please.yml
Update version of release-please reference in the github action
> chore: update release please version

- apps/imageHotspotCreator/.gitignore
- apps/imageHotspotCreator/LICENSE
- apps/imageHotspotCreator/README.md
- apps/imageHotspotCreator/jsdoc.json
- apps/imageHotspotCreator/package-lock.json
- apps/imageHotspotCreator/package.json
- apps/imageHotspotCreator/public/index.html
- apps/imageHotspotCreator/react-app-env.d.ts
- apps/imageHotspotCreator/src/App.tsx
- apps/imageHotspotCreator/src/components/Creator/createHotspot.css
- apps/imageHotspotCreator/src/components/Creator/createHotspot.tsx
- apps/imageHotspotCreator/src/components/Home/home.css
- apps/imageHotspotCreator/src/components/Home/home.tsx
- apps/imageHotspotCreator/src/components/Image Selector/selectImage.css
- apps/imageHotspotCreator/src/components/Image Selector/selectImage.tsx
- apps/imageHotspotCreator/src/components/LocalhostWarning.tsx
- apps/imageHotspotCreator/src/index.tsx
- apps/imageHotspotCreator/src/locations/EntryEditor.tsx
- apps/imageHotspotCreator/src/react-app-env.d.ts
- apps/imageHotspotCreator/src/setupTests.ts
- apps/imageHotspotCreator/test/mocks/index.ts
- apps/imageHotspotCreator/test/mocks/mockCma.ts
- apps/imageHotspotCreator/test/mocks/mockSdk.ts
- apps/imageHotspotCreator/tsconfig.json
Fixing build and pipeline issues,
> fix: delete .circlect directoy

- apps/imageHotspotCreator/package.json
To release Image Hotspot Creator
> chore: update imageHotspotCreator with correct app definitions

- apps/imageHotspotCreator/src/components/Creator/createHotspot.tsx
Fixing "can't set undefined value to setValue" issue.
> fix: Update createHotspot.tsx

- apps/imageHotspotCreator/src/components/Creator/createHotspot.css
CSS styling fixes in image hotspot creator
> fix: Update createHotspot.css

- apps/bynder/package-lock.json
- apps/bynder/package.json
Bump `dam-app-base` in Bynder so that we can have the latest version, which includes a quick fix to the asset card "more details" display.
Verified that the config page and field location render as expected.
> chore: bump dam-app-base in bynder app [INTEG-1627]

- .github/CODEOWNERS
- .release-please-manifest.json
- apps/bynder/package-lock.json
- apps/bynder/package.json
- apps/shopify/CHANGELOG.md
- apps/shopify/package-lock.json
- apps/shopify/package.json
- apps/shopify/src/index.js
Merge recent changes on main to production branch
> chore: merge main to production

- README.md
Adding additional guidance for partners when commiting
> chore: Update README.md to cover public commit messages []

- .github/workflows/dependabot-approve-and-request-merge.yml
Testing a fix for dependabot automerge. See https://github.com/contentful/github-auto-merge/pull/20
We'll revert / fix the code later if we confirm things work correctly. But the action doesn't run unless the change is already on the master branch.
> ci: test approve

- .github/workflows/dependabot-approve-and-request-merge.yml
> ci: experiment with new approve branch

- .github/workflows/dependabot-approve-and-request-merge.yml
@contentful/team-mechagodzilla had to revert the initial PR fixing dependabot approver and re-release the change as a v2.
* Upgrade and add required pull-request: write permission (though for whatever reason that permission didn't seem to be required for us)
> ci: upgrade dependabot approver

- .github/dependabot.yml
- apps/wix/package.json
This PR is getting the Wix app ready for the marketplace.
Two small updates:
- Add the deploy script with the new marketplace app id for Wix
- Add the Wix directory to our dependabot confog
> chore: update wix deploy script and dependabot [INTEG-1828]

- .github/CODEOWNERS
- catalog-info.yaml
Adds the `catalog-info.yaml` file to indicate ownership. Also updated `CODEOWNERS` to reflect current staffing.
Followed the pattern of what we have for the apps repo from the most part.
> chore: add catalog-info.yaml file and update CODEOWNERS [INTEG-1826]

- apps/wix/package-lock.json
- apps/wix/package.json
Change the wix app name in `package.json` to be consistent with other partner apps.
Change `@contentful/wix-integration` to `wix-contentful-app`.
> chore: update wix name in package.json []

- .github/dependabot.yml
Adds the new Intershop app to our dependabot config to help keep dependencies up to date.
> chore: add intershop to dependabot config []

- apps/cloudinary2/src/locations/Field/index.tsx
Cloudinary was broken with the new SDK changes, this handles the SDK returning null
> fix: handle null fields in cloudinary

- .github/CODEOWNERS
- catalog-info.yaml
Change `CODEOWNERS` from integrations to DX and update `catalog-info.yml` file.
> chore: update ownership to DX team [EXT-5221]

- apps/bynder-content-workflow/package.json
Adds deploy script for new Bynder CF app
> chore: Bynder CF deploy script []

- apps/bynder-content-workflow/package-lock.json
- apps/bynder-content-workflow/package.json
- apps/bynder-content-workflow/vite.config.ts
> fix: Bynder CF build config

- .github/dependabot.yml
disable dependabot updates across apps
> fix: disable root level dependabot updates

- apps/raster/package.json
[EXT-5671](https://contentful.atlassian.net/browse/EXT-5671)
[EXT-5671]: https://contentful.atlassian.net/browse/EXT-5671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: release Raster app [EXT-5671]

- release-please-config.json
> feat: add raster to release please

- apps/adapt-essentials-asset-fields/package-lock.json
- apps/adapt-essentials-asset-fields/package.json
- apps/adapt-essentials-asset-fields/src/components/AssetInputFieldText.tsx
- apps/adapt-essentials-asset-fields/src/components/BodyInputCellResolver.tsx
- apps/adapt-essentials-asset-fields/src/components/TagChooser.tsx
- apps/adapt-essentials-asset-fields/src/locations/ConfigScreen.tsx
Help **dependabot** with chore updates.
Fixed lint errors to make it smoother.
Updated and tested locally
> fix: update `apps/adapt-essentials-asset-fields` code to support updated lint rules

- .github/dependabot.yml
- apps/eppo/package-lock.json
- apps/eppo/package.json
- release-please-config.json
> chore: add deploy config for eppo

- .github/dependabot.yml
- release-please-config.json
Adds frontify deployment config
> chore: frontify deployment

- .github/workflows/new-app-review.yml
> fix: syntax error in workflows.yml

- .github/dependabot.yml
- apps/vwo-fme/package.json
- release-please-config.json
…e.json, add app to release-please config
> feat: add dependabot code for app, add deploy script to app's package.json[INTEG-2340]

- .github/dependabot.yml
- apps/sfmc-studio/package.json
- release-please-config.json
> feat: sfmc studio release

- apps/sfmc-studio/package-lock.json
- apps/sfmc-studio/package.json
> fix: sfmc studio add app scripts

- .github/workflows/pr-title-check.yml
Adds a GH workflow to check for either [] or [jira-1234]
> chore: Add PR title check workflow []

- apps/vwo-fme/src/App.jsx
- apps/vwo-fme/src/locations/ConfigScreen.jsx
We are updating the kb(knowledge base) link
> fix: new app vwo fme: update kb link

- .github/dependabot.yml
- apps/statsig/package.json
- release-please-config.json
Releasing the statsig app to prod
> chore: release statsig app [INTEG-2419]

- apps/statsig/src/locations/ConfigScreen.tsx
Need the statsigExperimentId in the API response to know which experiment to assign the user to.
> fix: add experiment id to api response []

- .github/workflows/dependabot-approve-and-request-merge.yml
- .github/workflows/lint-pull-requests.yml
- .github/workflows/new-app-review.yml
- .github/workflows/pr-title-check.yml
- .github/workflows/yaml-linter.yml
First pass to set up linting for yaml files
> chore: lint yml files with Yamllint workflow [INTEG-2453]

- catalog-info.yaml
adds service definitions for each marketplace partner app
> chore: add service definitions for marketplace partner apps [EXT-6259]

- .github/workflows/new-app-review.yml
- .github/workflows/new-app-review/validators/boilerplate.ts
- .github/workflows/new-app-review/validators/eslint.ts
- .github/workflows/new-app-review/validators/package-json.ts
- .github/workflows/new-app-review/validators/readme.ts
- .github/workflows/new-app-review/validators/typescript.ts
We want to automate some of our requirements on PRs
[INTEG-2376](https://contentful.atlassian.net/browse/INTEG-2376)
[INTEG-2376]: https://contentful.atlassian.net/browse/INTEG-2376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: pr requirements [INTEG-2376]

- .github/workflows/new-app-review.yml
> pointing workflow to main []

- .github/workflows/new-app-review/validators/package-json.ts
> including a check for test script before checking --passWithNoTests []

- .github/workflows/new-app-review/validators/eslint.ts
- .github/workflows/new-app-review/validators/package-json.ts
> removing console logs, cleaning up script messaging []

- apps/lottie-viewer/package-lock.json
- apps/lottie-viewer/package.json
- apps/lottie-viewer/src/locations/Field.test.tsx
- apps/lottie-viewer/vite.config.ts
[INTEG-2556](https://contentful.atlassian.net/browse/INTEG-2556)
[INTEG-2556]: https://contentful.atlassian.net/browse/INTEG-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: lottie viewer unit tests [INTEG-2556]

- .github/workflows/new-app-review/validators/typescript.ts
[INTEG-2519](https://contentful.atlassian.net/browse/INTEG-2519)
[INTEG-2519]: https://contentful.atlassian.net/browse/INTEG-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Update typescript validators [INTEG-2519]

- .github/workflows/new-app-review/validators/typescript.ts
[INTEG-2519](https://contentful.atlassian.net/browse/INTEG-2519)
[INTEG-2519]: https://contentful.atlassian.net/browse/INTEG-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Update typescript validator [INTEG-2519]

- apps/lottie-viewer/src/components/modals/JsonEditorModal.tsx
- apps/lottie-viewer/src/components/modals/JsonEditorModalTest.spec.tsx
- apps/lottie-viewer/src/components/modals/LottiePreviewModal.tsx
- apps/lottie-viewer/src/components/modals/LottiePreviewModalTest.spec.tsx
- apps/lottie-viewer/src/locations/Field.test.tsx
- apps/lottie-viewer/src/locations/Field.tsx
https://github.com/user-attachments/assets/de84ca95-37ab-4e98-9f4d-b0dc78ef1c5f
> feat: add modals to Lottie Preview Viewer for json and animation [INTEG-2552]

- .circleci/config.yml
- .github/workflows/delete-branch-on-close.yml
- .github/workflows/dependabot-approve-and-request-merge.yml
- .github/workflows/lint-pull-requests.yml
- .github/workflows/new-app-review.yml
- .github/workflows/pr-title-check.yml
- .github/workflows/release-and-deploy.yml
- .github/workflows/yaml-linter.yml
- apps/eppo/.github/workflows/build-test.yml
I was annoyed by the errors we were getting from our yaml linting so I fixed them
> fix: correct YAML formatting in new app review workflow []

- .github/dependabot.yml
- apps/convox/package.json
- release-please-config.json
These changes support maintaining and deploying the Convox app to the Contentful Marketplace.
> feat: Release Convox app [INTEG-2516]

- apps/convox/package.json
Updating the convox app to include a `deploy:staging` script. I missed that in the initial release.
> chore: add deploy:staging script for convox app [INTEG-2516]

- .github/dependabot.yml
- .release-please-manifest.json
- apps/lottie-viewer/package-lock.json
- apps/lottie-viewer/package.json
- apps/lottie-viewer/src/locations/Field.test.tsx
- release-please-config.json
Following the release steps for new app as detailed here: https://contentful.atlassian.net/wiki/spaces/ECO/pages/5210144895/Marketplace+Partner+Apps+-+Quick+Release+Guide+for+NEW+App+Submissions
> chore: lottie preview release [INTEG-2555]

- .release-please-manifest.json
> fix: release manifest syntax [INTEG-2555]

- .husky/pre-commit
- package-lock.json
- package.json
While Sarah was deploying the lottie-viewer app, we had to wait until the build/deploy completed in main before finding this issue 
https://github.com/contentful/marketplace-partner-apps/actions/runs/14671237097/job/41178023695
So this PR will ensure that 
1. JSON issues will be caught before merging PRs
2. Prevent build failures due to JSON issues 
Examples of success and failures
> fix: check json errors in project []

- apps/lottie-preview/package-lock.json
- apps/lottie-preview/package.json
Reverts contentful/marketplace-partner-apps#4931
> Revert "chore(deps-dev): bump the dev-dependencies group in /apps/lottie-preview with 2 updates []"

- apps/hugging-face/package.json
- apps/hugging-face/src/components/GenerateImageModal/GenerateImageModal.spec.tsx
- apps/hugging-face/src/components/GenerateImageModal/GenerateImageModal.tsx
- apps/hugging-face/src/components/InitialPrompt/InitialPrompt.tsx
- apps/hugging-face/src/components/RefinePromptModal/RefinePromptModal.spec.tsx
- apps/hugging-face/src/components/RefinePromptModal/RefinePromptModal.tsx
- apps/hugging-face/src/components/SaveAssetModal/SaveAssetModal.spec.tsx
- apps/hugging-face/src/components/SaveAssetModal/SaveAssetModal.styles.ts
- apps/hugging-face/src/components/SaveAssetModal/SaveAssetModal.tsx
- apps/hugging-face/src/locations/Page.spec.tsx
- apps/hugging-face/src/locations/Page.tsx
- apps/hugging-face/src/services/huggingfaceImage.ts
- apps/hugging-face/src/services/huggingfaceText.ts
- apps/hugging-face/src/services/uploadAsset.ts
- apps/lottie-preview/LICENSE
After creating image, name and save it to your asset library 
https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/454?selectedIssue=INTEG-2583
https://www.loom.com/share/fa7a8ba3d3214d428415d1e80a1358c4?sid=349fb20f-a29c-45a1-9b7f-4169842ff25f
> fix: hugging face add ability to save asset [INTEG-2583]

- apps/hugging-face/src/locations/ConfigScreen.tsx
- apps/hugging-face/src/services/huggingfaceImage.ts
- apps/hugging-face/src/utils/types.ts
Image gen was using default, low, settings. I added config + reasonable defaults
> feat: add image generation settings for Hugging Face [INTEG-2648]

- .github/dependabot.yml
- apps/hugging-face/package.json
- release-please-config.json
> chore: Hugging Face release conf [INTEG-2652]

- apps/hugging-face/src/components/GenerateImageModal/GenerateImageModal.tsx
- apps/hugging-face/src/locations/ConfigScreen.tsx
- apps/hugging-face/src/locations/Page.spec.tsx
- apps/hugging-face/src/services/uploadAsset.ts
- Use space default locale instead of en-us
- Use better default params for config model options
- fix the dang tests
> feat: post release cleanup [INTEG-2586]

- release-please-config.json
> fix: release-please config [INTEG-2668]

- apps/hugging-face/package.json
> fix: update deploy scripts to use ./dist directory [INTEG-2586]

- apps/vwo-fme/package-lock.json
- apps/vwo-fme/package.json
Reverts contentful/marketplace-partner-apps#4941
> fix: REVERT: bump contentful-management from 10.46.4 to 11.52.2 in /apps/vwo-fme []"

- .github/workflows/app-review-utils.ts
- .github/workflows/new-app-review.yml
> fix: changes to new app review to use correct "on" []

- .github/workflows/dependabot-approve-and-request-merge.yml
- .github/workflows/lint-pull-requests.yml
- .github/workflows/new-app-review.yml
cleaning up permissions for workflows
> refactor: app submission workflow fixes [INTEG-2578]

- apps/cloudinary2/.env
- apps/cloudinary2/src/constants.ts
- apps/cloudinary2/src/locations/ConfigScreen/InstallParamsConfiguration.spec.tsx
- apps/cloudinary2/src/locations/ConfigScreen/InstallParamsConfiguration.tsx
- apps/cloudinary2/src/locations/ConfigScreen/index.tsx
- apps/cloudinary2/src/locations/Dialog.tsx
- apps/cloudinary2/src/locations/Field/OpenDialogButton.tsx
- apps/cloudinary2/src/locations/Field/Thumbnail.tsx
- apps/cloudinary2/src/locations/Field/Thumbnails.tsx
- apps/cloudinary2/src/types.ts
- apps/cloudinary2/src/vite-env.d.ts
some minor UX changes allowing better experience for the app user 
1. showing video preview inline
2. click to edit cloudinary assets 
3. context menu action 'Edit in Cloudinary' opens as a modal instead of new window
https://github.com/user-attachments/assets/66f8dd71-4a70-49b5-9a99-0c23f611ee89
Added configuration to allow / block asset uploading from the media library.
https://github.com/user-attachments/assets/1785c032-4186-4989-b25d-cbdb93fb3cc4
> feat: Cloudinary thumbnail "click to edit" []

- .github/dependabot.yml
- apps/translationstudio/package.json
- release-please-config.json
Adds the necessary code to have the app deploy to prod
> feat: add translationstudio release code [INTEG-2528]

- apps/deep-clone-main/package-lock.json
- apps/lottie-preview/package-lock.json
- apps/lottie-preview/package.json
- apps/lottie-preview/src/App.tsx
- apps/lottie-preview/src/components/content-entry/LottieEditorHeader.tsx
- apps/lottie-preview/src/components/field/LottiePreviewField.test.tsx
- apps/lottie-preview/src/components/field/LottiePreviewField.tsx
- apps/lottie-preview/src/components/modals/JsonEditorModal.tsx
- apps/lottie-preview/src/components/modals/JsonEditorModalTest.spec.tsx
- apps/lottie-preview/src/components/modals/LottiePreviewModal.tsx
- apps/lottie-preview/src/components/modals/LottiePreviewModalTest.spec.tsx
- apps/lottie-preview/src/locations/ConfigScreen.test.tsx
- apps/lottie-preview/src/locations/Field.test.tsx
- apps/lottie-preview/src/locations/Field.tsx
- apps/lottie-preview/tsconfig.json
- apps/lottie-preview/vite.config.ts
https://github.com/user-attachments/assets/43cb14f9-8ebf-4c80-92d3-7748b9f21fd2
> fix: lottie-preview to build correctly in circleci []

- apps/bynder-content-workflow/.npmrc
- apps/bynder-content-workflow/package-lock.json
- apps/bynder-content-workflow/package.json
> chore: remove unused dependency nanoid [INTEG-2999]

- apps/docs-to-rich-text/package-lock.json
- apps/docs-to-rich-text/package.json
Fix for docs to rich text due to broken field-editor-rich-text package
> fix: roll back field editor rich text package update in docs to rich text app [INTEG-3004]
